server:
  port: 8080
  basePath: "/api/order-ease/v1"
  host: "0.0.0.0"
  domain: "xhgscdzdvzsl.sealoshzh.site"
  allowedOrigins:
    - "https://xhgscdzdvzsl.sealoshzh.site"
    - "https://xhgscdzdvzsl.sealoshzh.site"

database:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123456
  dbname: mysql
  charset: utf8mb4
  parseTime: true
  loc: Local 

jwt:
  secret: "e6jf493kdhbms9ew6mv2v1a4dx2"  # 建议使用随机生成的复杂字符串
  expiration: 7200  # token过期时间，单位为秒（2小时） 