server:
  port: 8080
  basePath: "/api/v1"
  host: "0.0.0.0"
  domain: "xhgscdzdvzsl.sealoshzh.site"
  allowedOrigins:
    - "https://xhgscdzdvzsl.sealoshzh.site"
    - "https://xhgscdzdvzsl.sealoshzh.site"

database:
  driver: mysql
  host: test-db-mysql.ns-ojjsi3o6.svc
  port: 3306
  username: root
  password: kjx2m6xx
  dbname: mysql
  charset: utf8mb4
  parseTime: true
  loc: Local 