// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject
// +build !wireinject

package services

import (
	"gorm.io/gorm"
	"orderease/infrastructure/repositories"
)

// InitializeServiceContainer 是由 Wire 生成的依赖注入函数
// 它会自动创建所有必需的 Repository、Service 并组装成 ServiceContainer
func InitializeServiceContainer(db *gorm.DB) (*ServiceContainer, error) {
	orderRepository := repositories.NewOrderRepository(db)
	orderItemRepository := repositories.NewOrderItemRepository(db)
	orderItemOptionRepository := repositories.NewOrderItemOptionRepository(db)
	orderStatusLogRepository := repositories.NewOrderStatusLogRepository(db)
	productRepository := repositories.NewProductRepository(db)
	productOptionCategoryRepository := repositories.NewProductOptionCategoryRepository(db)
	productOptionRepository := repositories.NewProductOptionRepository(db)
	productTagRepository := repositories.NewProductTagRepository(db)
	shopRepository := repositories.NewShopRepository(db)
	tagRepository := repositories.NewTagRepository(db)
	userRepository := repositories.NewUserRepository(db)

	orderService := NewOrderService(db, productRepository, productOptionRepository, productOptionCategoryRepository, orderRepository, orderItemRepository, orderItemOptionRepository, orderStatusLogRepository)
	productService := NewProductService(productRepository, productOptionCategoryRepository, productOptionRepository, productTagRepository, db)
	shopService := NewShopService(shopRepository, tagRepository, productRepository, db)
	userService := NewUserService(userRepository, db)
	tempTokenService := NewTempTokenService(db)

	serviceContainer := NewServiceContainer(orderService, productService, shopService, userService, tempTokenService)
	return serviceContainer, nil
}
